---
# handlers file for ansible-role-cuda
- name: reload systemd unit files
  shell: systemctl daemon-reload

- name: CUDA Restart server
  command: sleep 2 && /sbin/shutdown -r now "Node software upgrade reboot"
  async: 1
  poll: 0
  ignore_errors: true
  when:
    - cuda_packages_installation.changed
    - cuda_restart_node_on_install

# define the variable running_as_ansible_pull in the ansible-pull playbook, like local.yml 
- name: CUDA Wait for server to restart
  wait_for:
    host: "{{ ansible_ssh_host | default(inventory_hostname) }}"
    state: started
    delay: 30
    timeout: 300
  connection: local
  become: false
  when:
    - cuda_restart_node_on_install
    - (running_as_ansible_pull is not defined or running_as_ansible_pull == False)

# vim:ft=ansible:
